%% list_solvers
%%
%% Displays a list of recommended iterative solvers for use with this project.
%%
%% This helper script provides a curated list of iterative solvers that are
%% available in Octave and are generally suitable for solving the non-symmetric
%% sparse linear systems generated by the SPN analysis.
%%
%% The output includes the name of the solver and a brief description of its
%% characteristics. This helps the user make an informed choice when using
%% the `benchmark_solvers` script.
%%
%% Usage:
%%   octave --eval "list_solvers"

function list_solvers()
  fprintf('--- Recommended Iterative Solvers ---\n\n');

  fprintf('The following iterative solvers are available in Octave and are suitable for the\n');
  fprintf('non-symmetric systems generated by this SPN analysis tool.\n\n');

  fprintf('  Solver Name   | Description\n');
  fprintf('----------------|-------------------------------------------------------------\n');

  fprintf('  gmres         | (Generalized Minimum Residual) A good general-purpose\n');
  fprintf('                | method, often a first choice for non-symmetric systems.\n\n');

  fprintf('  bicg          | (Bi-Conjugate Gradients) A variant of the Conjugate\n');
  fprintf('                | Gradients method for non-symmetric square matrices.\n\n');

  fprintf('  bicgstab      | (Bi-Conjugate Gradients Stabilized) A stabilized version\n');
  fprintf('                | of BiCG that often provides faster and smoother convergence.\n\n');

  fprintf('  cgs           | (Conjugate Gradients Squared) Another variant of BiCG that\n');
  fprintf('                | can offer faster convergence but may be less stable.\n\n');

  fprintf('Example usage with the benchmark script:\n');
  fprintf('  benchmark_solvers([100, 500], {\'gmres\', \'bicgstab\'});\n\n');
endfunction