function generate_html_report(filepath, stats)
  % GENERATE_HTML_REPORT Writes an HTML summary report of the dataset.

  fid = fopen(filepath, "w");
  if fid < 0
    error("Failed to create report file: %s", filepath);
  endif

  html_template = sprintf([ ...
    "<!DOCTYPE html>\n" ...
    "<html>\n" ...
    "<head>\n" ...
    "\t<title>SPN Dataset Statistics</title>\n" ...
    "\t<style>\n" ...
    "\t\tbody { font-family: sans-serif; }\n" ...
    "\t\ttable { border-collapse: collapse; }\n" ...
    "\t\tth, td { border: 1px solid #ddd; padding: 8px; }\n" ...
    "\t\tth { background-color: #f2f2f2; }\n" ...
    "\t</style>\n" ...
    "</head>\n" ...
    "<body>\n" ...
    "\t<h1>SPN Dataset Statistics</h1>\n" ...
    "\t<table>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<th>Statistic</th>\n" ...
    "\t\t\t<th>Value</th>\n" ...
    "\t\t</tr>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<td>Number of samples</td>\n" ...
    "\t\t\t<td>%d</td>\n" ...
    "\t\t</tr>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<td>Average number of places</td>\n" ...
    "\t\t\t<td>%.2f</td>\n" ...
    "\t\t</tr>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<td>Average number of transitions</td>\n" ...
    "\t\t\t<td>%.2f</td>\n" ...
    "\t\t</tr>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<td>Average number of markings</td>\n" ...
    "\t\t\t<td>%.2f</td>\n" ...
    "\t\t</tr>\n" ...
    "\t\t<tr>\n" ...
    "\t\t\t<td>Average steady-state probabilities</td>\n" ...
    "\t\t\t<td>%.2f</td>\n" ...
    "\t\t</tr>\n" ...
    "\t</table>\n" ...
    "</body>\n" ...
    "</html>\n" ...
  ], stats.num_samples, stats.avg_places, stats.avg_transitions, stats.avg_markings, stats.avg_steady_state_probs);

  fprintf(fid, "%s", html_template);
  fclose(fid);
endfunction
